"""Generate seed JSON files for all 18 domains with 10 high-quality URLs each."""
import json
from pathlib import Path

SEED_DIR = Path(__file__).parent.parent / "storage" / "seed"
SEED_DIR.mkdir(parents=True, exist_ok=True)

SEEDS = {
    "Medicine": [
        {"title": "Medicine - Wikipedia", "url": "https://en.wikipedia.org/wiki/Medicine", "trust": 70, "tier": 2, "description": "Overview of medical science, practice, and healthcare systems."},
        {"title": "PubMed Central", "url": "https://www.ncbi.nlm.nih.gov/pmc/", "trust": 100, "tier": 1, "description": "Free full-text archive of biomedical and life sciences journal literature."},
        {"title": "WHO - Health Topics", "url": "https://www.who.int/health-topics", "trust": 100, "tier": 1, "description": "World Health Organization resources on global health topics."},
        {"title": "Mayo Clinic - Diseases", "url": "https://www.mayoclinic.org/diseases-conditions", "trust": 85, "tier": 1, "description": "Comprehensive medical information on diseases and conditions."},
        {"title": "NIH - National Institutes of Health", "url": "https://www.nih.gov/health-information", "trust": 100, "tier": 1, "description": "US National Institutes of Health, medical research and health information."},
        {"title": "The Lancet", "url": "https://www.thelancet.com/", "trust": 95, "tier": 1, "description": "Peer-reviewed medical journal, high-impact clinical research."},
        {"title": "BMJ - British Medical Journal", "url": "https://www.bmj.com/", "trust": 95, "tier": 1, "description": "One of the world's oldest peer-reviewed medical journals."},
        {"title": "CDC - Centers for Disease Control", "url": "https://www.cdc.gov/", "trust": 100, "tier": 1, "description": "US public health agency, disease prevention and health promotion."},
        {"title": "MedlinePlus", "url": "https://medlineplus.gov/", "trust": 100, "tier": 1, "description": "NIH patient health information in multiple languages."},
        {"title": "Cochrane Library", "url": "https://www.cochranelibrary.com/", "trust": 100, "tier": 1, "description": "Systematic reviews and meta-analyses for evidence-based medicine."},
    ],
    "Physics": [
        {"title": "Physics - Wikipedia", "url": "https://en.wikipedia.org/wiki/Physics", "trust": 70, "tier": 2, "description": "Overview of physics, its branches, and fundamental theories."},
        {"title": "ArXiv Physics", "url": "https://arxiv.org/list/physics/new", "trust": 100, "tier": 1, "description": "Preprint repository for physics research papers."},
        {"title": "Physics Today", "url": "https://pubs.aip.org/physicstoday", "trust": 85, "tier": 1, "description": "American Institute of Physics magazine covering all physics."},
        {"title": "CERN - Physics", "url": "https://home.cern/science/physics", "trust": 100, "tier": 1, "description": "CERN research in particle physics and fundamental science."},
        {"title": "APS Physics", "url": "https://www.aps.org/", "trust": 95, "tier": 1, "description": "American Physical Society, publisher of Physical Review journals."},
        {"title": "Nature Physics", "url": "https://www.nature.com/nphys/", "trust": 95, "tier": 1, "description": "Leading physics journal publishing peer-reviewed research."},
        {"title": "NASA - Physics", "url": "https://science.nasa.gov/physics", "trust": 100, "tier": 1, "description": "NASA physics research in astrophysics, heliophysics, and more."},
        {"title": "Institute of Physics", "url": "https://www.iop.org/", "trust": 90, "tier": 1, "description": "UK Institute of Physics, research and education resources."},
        {"title": "Stanford Encyclopedia - Physics", "url": "https://plato.stanford.edu/entries/physics/", "trust": 100, "tier": 1, "description": "Stanford Encyclopedia of Philosophy entry on physics."},
        {"title": "MIT Physics", "url": "https://web.mit.edu/physics/", "trust": 100, "tier": 1, "description": "MIT Department of Physics research and education."},
    ],
    "Cybersecurity": [
        {"title": "Cybersecurity - Wikipedia", "url": "https://en.wikipedia.org/wiki/Computer_security", "trust": 70, "tier": 2, "description": "Overview of computer security, threats, and defenses."},
        {"title": "NIST Cybersecurity", "url": "https://www.nist.gov/cybersecurity", "trust": 100, "tier": 1, "description": "US National Institute of Standards and Technology cybersecurity framework."},
        {"title": "OWASP", "url": "https://owasp.org/", "trust": 95, "tier": 1, "description": "Open Web Application Security Project, web application security."},
        {"title": "MITRE ATT&CK", "url": "https://attack.mitre.org/", "trust": 100, "tier": 1, "description": "Knowledge base of adversary tactics and techniques."},
        {"title": "SANS Institute", "url": "https://www.sans.org/", "trust": 85, "tier": 1, "description": "Information security training and certification resources."},
        {"title": "US-CERT", "url": "https://www.cisa.gov/cybersecurity", "trust": 100, "tier": 1, "description": "CISA cybersecurity alerts, advisories, and best practices."},
        {"title": "ENISA", "url": "https://www.enisa.europa.eu/", "trust": 95, "tier": 1, "description": "European Union Agency for Cybersecurity, policy and research."},
        {"title": "ArXiv Cryptography", "url": "https://arxiv.org/list/cs.CR/new", "trust": 100, "tier": 1, "description": "Preprints in cryptography and security (cs.CR)."},
        {"title": "IACR", "url": "https://iacr.org/", "trust": 95, "tier": 1, "description": "International Association for Cryptologic Research."},
        {"title": "Krebs on Security", "url": "https://krebsonsecurity.com/", "trust": 75, "tier": 2, "description": "In-depth cybersecurity news and investigation by Brian Krebs."},
    ],
    "SoftwareEngineering": [
        {"title": "Software Engineering - Wikipedia", "url": "https://en.wikipedia.org/wiki/Software_engineering", "trust": 70, "tier": 2, "description": "Overview of software engineering principles and methodologies."},
        {"title": "IEEE Software", "url": "https://www.computer.org/csdl/magazines/so", "trust": 95, "tier": 1, "description": "IEEE magazine on software engineering practice and research."},
        {"title": "ACM SIGSOFT", "url": "https://www.sigsoft.org/", "trust": 95, "tier": 1, "description": "ACM Special Interest Group on Software Engineering."},
        {"title": "SEI - Carnegie Mellon", "url": "https://www.sei.cmu.edu/", "trust": 100, "tier": 1, "description": "Software Engineering Institute at CMU, best practices and standards."},
        {"title": "ArXiv Software Engineering", "url": "https://arxiv.org/list/cs.SE/new", "trust": 100, "tier": 1, "description": "Preprints in software engineering (cs.SE)."},
        {"title": "Google Engineering Practices", "url": "https://google.github.io/eng-practices/", "trust": 85, "tier": 1, "description": "Google's engineering practices documentation."},
        {"title": "Martin Fowler's Bliki", "url": "https://martinfowler.com/", "trust": 85, "tier": 1, "description": "Thoughts on software design, architecture, and refactoring."},
        {"title": "12factor App", "url": "https://12factor.net/", "trust": 70, "tier": 2, "description": "Methodology for building SaaS applications."},
        {"title": "Microsoft Dev Center", "url": "https://learn.microsoft.com/en-us/azure/architecture/", "trust": 85, "tier": 1, "description": "Microsoft Azure architecture guidance and best practices."},
        {"title": "Semantic Scholar SE", "url": "https://www.semanticscholar.org/topic/Software-engineering", "trust": 85, "tier": 1, "description": "AI-powered research tool for software engineering papers."},
    ],
    "Mathematics": [
        {"title": "Mathematics - Wikipedia", "url": "https://en.wikipedia.org/wiki/Mathematics", "trust": 70, "tier": 2, "description": "Overview of mathematics, its branches, and history."},
        {"title": "ArXiv Mathematics", "url": "https://arxiv.org/list/math/new", "trust": 100, "tier": 1, "description": "Preprints in all areas of mathematics."},
        {"title": "AMS - American Mathematical Society", "url": "https://www.ams.org/", "trust": 100, "tier": 1, "description": "Professional society, journals, and mathematical reviews."},
        {"title": "MathWorld - Wolfram", "url": "https://mathworld.wolfram.com/", "trust": 85, "tier": 1, "description": "Comprehensive mathematics encyclopedia by Wolfram Research."},
        {"title": "PlanetMath", "url": "https://planetmath.org/", "trust": 70, "tier": 2, "description": "Peer-reviewed collaborative mathematics encyclopedia."},
        {"title": "Stanford Encyclopedia - Mathematics", "url": "https://plato.stanford.edu/entries/mathematics/", "trust": 100, "tier": 1, "description": "SEP entry on the philosophy of mathematics."},
        {"title": "nLab", "url": "https://ncatlab.org/nlab/show/HomePage", "trust": 70, "tier": 2, "description": "Wiki on mathematics, physics, and philosophy."},
        {"title": "SIAM", "url": "https://www.siam.org/", "trust": 95, "tier": 1, "description": "Society for Industrial and Applied Mathematics."},
        {"title": "MathOverflow", "url": "https://mathoverflow.net/", "trust": 70, "tier": 2, "description": "Q&A site for professional mathematicians."},
        {"title": "MacTutor History of Mathematics", "url": "https://mathshistory.st-andrews.ac.uk/", "trust": 95, "tier": 1, "description": "University of St Andrews biographies and history of mathematics."},
    ],
    "DataScience": [
        {"title": "Data Science - Wikipedia", "url": "https://en.wikipedia.org/wiki/Data_science", "trust": 70, "tier": 2, "description": "Overview of data science methods, tools, and applications."},
        {"title": "KDnuggets", "url": "https://www.kdnuggets.com/", "trust": 75, "tier": 2, "description": "Data science, machine learning, and analytics news and tutorials."},
        {"title": "ArXiv Machine Learning", "url": "https://arxiv.org/list/cs.LG/new", "trust": 100, "tier": 1, "description": "Preprints in machine learning (cs.LG)."},
        {"title": "Google AI", "url": "https://ai.google/research/", "trust": 95, "tier": 1, "description": "Google AI research publications and resources."},
        {"title": "OpenAI Research", "url": "https://openai.com/research/", "trust": 85, "tier": 1, "description": "OpenAI research papers and technical reports."},
        {"title": "Papers With Code", "url": "https://paperswithcode.com/", "trust": 85, "tier": 1, "description": "Machine learning papers with code implementations and benchmarks."},
        {"title": "Scikit-learn Documentation", "url": "https://scikit-learn.org/stable/user_guide.html", "trust": 95, "tier": 1, "description": "Official scikit-learn user guide and tutorials."},
        {"title": "Towards Data Science", "url": "https://towardsdatascience.com/", "trust": 60, "tier": 2, "description": "Medium publication covering data science topics."},
        {"title": "StatLib - CMU", "url": "https://lib.stat.cmu.edu/", "trust": 100, "tier": 1, "description": "Carnegie Mellon University statistical software and datasets."},
        {"title": "NeurIPS Proceedings", "url": "https://papers.nips.cc/", "trust": 100, "tier": 1, "description": "Advances in Neural Information Processing Systems proceedings."},
    ],
    "Electronics": [
        {"title": "Electronics - Wikipedia", "url": "https://en.wikipedia.org/wiki/Electronics", "trust": 70, "tier": 2, "description": "Overview of electronics, components, and circuits."},
        {"title": "IEEE Xplore", "url": "https://ieeexplore.ieee.org/", "trust": 100, "tier": 1, "description": "IEEE journals, conferences, and standards in electronics."},
        {"title": "ArXiv Electronics", "url": "https://arxiv.org/list/cs.ET/new", "trust": 100, "tier": 1, "description": "Preprints in emerging technologies (cs.ET), including electronics."},
        {"title": "All About Circuits", "url": "https://www.allaboutcircuits.com/", "trust": 75, "tier": 2, "description": "Electronics tutorials, technical articles, and resources."},
        {"title": "EDN Network", "url": "https://www.edn.com/", "trust": 70, "tier": 2, "description": "Electronic design news and engineering resources."},
        {"title": "TI E2E Community", "url": "https://e2e.ti.com/", "trust": 85, "tier": 1, "description": "Texas Instruments engineering community and technical documentation."},
        {"title": "Analog Devices Wiki", "url": "https://wiki.analog.com/", "trust": 85, "tier": 1, "description": "Analog Devices technical documentation and tutorials."},
        {"title": "ArXiv Signal Processing", "url": "https://arxiv.org/list/eess.SP/new", "trust": 100, "tier": 1, "description": "Preprints in signal processing (eess.SP)."},
        {"title": "Electronics Tutorials", "url": "https://www.electronics-tutorials.ws/", "trust": 65, "tier": 2, "description": "Free online electronics tutorials and resources."},
        {"title": "Digi-Key Tech Forum", "url": "https://www.digikey.com/en/tech-forum", "trust": 70, "tier": 2, "description": "Electronics component distributor technical content."},
    ],
    "Chemistry": [
        {"title": "Chemistry - Wikipedia", "url": "https://en.wikipedia.org/wiki/Chemistry", "trust": 70, "tier": 2, "description": "Overview of chemistry, its branches, and fundamental concepts."},
        {"title": "ACS - American Chemical Society", "url": "https://www.acs.org/", "trust": 100, "tier": 1, "description": "Professional society with journals, conferences, and education resources."},
        {"title": "PubChem", "url": "https://pubchem.ncbi.nlm.nih.gov/", "trust": 100, "tier": 1, "description": "NIH open chemistry database of chemical molecules."},
        {"title": "ArXiv Chemistry", "url": "https://arxiv.org/list/chem/new", "trust": 100, "tier": 1, "description": "Preprints in chemistry."},
        {"title": "RSC - Royal Society of Chemistry", "url": "https://www.rsc.org/", "trust": 100, "tier": 1, "description": "UK professional society for chemistry with journals and resources."},
        {"title": "Nature Chemistry", "url": "https://www.nature.com/nchem/", "trust": 95, "tier": 1, "description": "Leading chemistry journal publishing peer-reviewed research."},
        {"title": "ChemSpider", "url": "https://www.chemspider.com/", "trust": 85, "tier": 1, "description": "Free chemical structure database by RSC."},
        {"title": "NIST Chemistry WebBook", "url": "https://webbook.nist.gov/chemistry/", "trust": 100, "tier": 1, "description": "NIST Standard Reference Database for chemical species."},
        {"title": "IUPAC", "url": "https://iupac.org/", "trust": 100, "tier": 1, "description": "International Union of Pure and Applied Chemistry standards."},
        {"title": "Journal of the American Chemical Society", "url": "https://pubs.acs.org/journal/jacsat", "trust": 100, "tier": 1, "description": "Flagship journal of the American Chemical Society."},
    ],
    "Astronomy": [
        {"title": "Astronomy - Wikipedia", "url": "https://en.wikipedia.org/wiki/Astronomy", "trust": 70, "tier": 2, "description": "Overview of astronomy, its history, and subfields."},
        {"title": "NASA - Astronomy", "url": "https://science.nasa.gov/astronomy", "trust": 100, "tier": 1, "description": "NASA astronomy research, missions, and education resources."},
        {"title": "ArXiv Astrophysics", "url": "https://arxiv.org/list/astro-ph/new", "trust": 100, "tier": 1, "description": "Preprints in astrophysics (astro-ph)."},
        {"title": "ESO - European Southern Observatory", "url": "https://www.eso.org/", "trust": 100, "tier": 1, "description": "ESO astronomical observatory and research."},
        {"title": "Hubble Space Telescope", "url": "https://hubblesite.org/", "trust": 100, "tier": 1, "description": "Hubble Space Telescope discoveries and resources."},
        {"title": "AAS - American Astronomical Society", "url": "https://aas.org/", "trust": 100, "tier": 1, "description": "Professional society for astronomers."},
        {"title": "Sky & Telescope", "url": "https://skyandtelescope.org/", "trust": 75, "tier": 2, "description": "Astronomy magazine for enthusiasts and professionals."},
        {"title": "NASA ADS", "url": "https://ui.adsabs.harvard.edu/", "trust": 100, "tier": 1, "description": "NASA Astrophysics Data System, bibliographic database."},
        {"title": "International Astronomical Union", "url": "https://www.iau.org/", "trust": 100, "tier": 1, "description": "International authority for astronomical nomenclature."},
        {"title": "Planetary Society", "url": "https://www.planetary.org/", "trust": 85, "tier": 1, "description": "Nonprofit dedicated to space exploration and planetary science."},
    ],
    "PhilosophyHistory": [
        {"title": "Philosophy - Wikipedia", "url": "https://en.wikipedia.org/wiki/Philosophy", "trust": 70, "tier": 2, "description": "Overview of philosophy, its branches, and history."},
        {"title": "Stanford Encyclopedia of Philosophy", "url": "https://plato.stanford.edu/", "trust": 100, "tier": 1, "description": "Peer-reviewed encyclopedia of philosophy by Stanford University."},
        {"title": "Internet Encyclopedia of Philosophy", "url": "https://iep.utm.edu/", "trust": 85, "tier": 1, "description": "Free online encyclopedia of philosophy."},
        {"title": "PhilPapers", "url": "https://philpapers.org/", "trust": 85, "tier": 1, "description": "Comprehensive index and bibliography of philosophy."},
        {"title": "History - Wikipedia", "url": "https://en.wikipedia.org/wiki/History", "trust": 70, "tier": 2, "description": "Overview of historical methodology and world history."},
        {"title": "Persée", "url": "https://www.persee.fr/", "trust": 85, "tier": 1, "description": "French digital library for humanities and social sciences."},
        {"title": "JSTOR Philosophy", "url": "https://www.jstor.org/subject/philosophy", "trust": 95, "tier": 1, "description": "Digital library for philosophy academic journals."},
        {"title": "British Academy", "url": "https://www.thebritishacademy.ac.uk/", "trust": 85, "tier": 1, "description": "UK national academy for humanities and social sciences."},
        {"title": "ArXiv History", "url": "https://arxiv.org/list/cs.GL/new", "trust": 80, "tier": 2, "description": "General literature preprints including history of science."},
        {"title": "Philosophy Compass", "url": "https://compass.onlinelibrary.wiley.com/philo", "trust": 85, "tier": 1, "description": "Peer-reviewed survey articles in philosophy."},
    ],
    "ArtHistory": [
        {"title": "Art History - Wikipedia", "url": "https://en.wikipedia.org/wiki/Art_history", "trust": 70, "tier": 2, "description": "Overview of art history, methods, and periods."},
        {"title": "Metropolitan Museum of Art - Heilbrunn Timeline", "url": "https://www.metmuseum.org/toah/", "trust": 100, "tier": 1, "description": "Comprehensive art history timeline from the Met."},
        {"title": "Getty Research Institute", "url": "https://www.getty.edu/research/", "trust": 100, "tier": 1, "description": "Art history research resources and publications."},
        {"title": "Smarthistory", "url": "https://smarthistory.org/", "trust": 85, "tier": 1, "description": "Free art history resources and multimedia content."},
        {"title": "Khan Academy - Art History", "url": "https://www.khanacademy.org/humanities/art-history", "trust": 85, "tier": 1, "description": "Comprehensive art history course and materials."},
        {"title": "Victoria and Albert Museum", "url": "https://www.vam.ac.uk/", "trust": 100, "tier": 1, "description": "World's largest museum of decorative arts and design."},
        {"title": "British Museum", "url": "https://www.britishmuseum.org/collection", "trust": 100, "tier": 1, "description": "British Museum collection for art historical research."},
        {"title": "ArXiv Art History", "url": "https://arxiv.org/list/cs.CV/new", "trust": 70, "tier": 2, "description": "Computer vision preprints applied to art analysis (cs.CV)."},
        {"title": "Oxford Art Online", "url": "https://www.oxfordartonline.com/", "trust": 100, "tier": 1, "description": "Oxford University Press art reference works."},
        {"title": "National Gallery of Art", "url": "https://www.nga.gov/", "trust": 100, "tier": 1, "description": "US National Gallery collections and art historical research."},
    ],
    "FinanceEconomics": [
        {"title": "Economics - Wikipedia", "url": "https://en.wikipedia.org/wiki/Economics", "trust": 70, "tier": 2, "description": "Overview of economics, microeconomics, and macroeconomics."},
        {"title": "NBER - National Bureau of Economic Research", "url": "https://www.nber.org/", "trust": 100, "tier": 1, "description": "Leading nonprofit economic research organization."},
        {"title": "IMF - International Monetary Fund", "url": "https://www.imf.org/en/Publications", "trust": 100, "tier": 1, "description": "IMF research and publications on global economics."},
        {"title": "World Bank Open Knowledge Repository", "url": "https://openknowledge.worldbank.org/", "trust": 100, "tier": 1, "description": "World Bank research and data on development economics."},
        {"title": "Federal Reserve Economic Data (FRED)", "url": "https://fred.stlouisfed.org/", "trust": 100, "tier": 1, "description": "St Louis Fed economic data and research."},
        {"title": "ArXiv Finance", "url": "https://arxiv.org/list/q-fin/new", "trust": 100, "tier": 1, "description": "Preprints in quantitative finance (q-fin)."},
        {"title": "SSRN Economics", "url": "https://papers.ssrn.com/sol3/JELJOUR_Results.cfm", "trust": 85, "tier": 1, "description": "Social Science Research Network, economics preprints."},
        {"title": "Journal of Finance", "url": "https://onlinelibrary.wiley.com/journal/15406261", "trust": 95, "tier": 1, "description": "Leading journal in financial economics."},
        {"title": "BIS - Bank for International Settlements", "url": "https://www.bis.org/", "trust": 100, "tier": 1, "description": "Central bank for central banks, financial stability research."},
        {"title": "OECD Economics", "url": "https://www.oecd.org/en/topics/economic-policy.html", "trust": 100, "tier": 1, "description": "OECD economic policy analysis and data."},
    ],
    "LegalSystem": [
        {"title": "Law - Wikipedia", "url": "https://en.wikipedia.org/wiki/Law", "trust": 70, "tier": 2, "description": "Overview of legal systems, branches, and jurisprudence."},
        {"title": "Cornell Legal Information Institute", "url": "https://www.law.cornell.edu/", "trust": 100, "tier": 1, "description": "Free US legal research and resources from Cornell Law."},
        {"title": "SSRN Legal Scholarship", "url": "https://papers.ssrn.com/sol3/JELJOUR_Results.cfm", "trust": 85, "tier": 1, "description": "Social Science Research Network legal studies preprints."},
        {"title": "Justia", "url": "https://www.justia.com/", "trust": 75, "tier": 2, "description": "Free US legal resources, case law, and codes."},
        {"title": "European Court of Human Rights", "url": "https://www.echr.coe.int/", "trust": 100, "tier": 1, "description": "ECHR judgments and case law database."},
        {"title": "UN Treaty Collection", "url": "https://treaties.un.org/", "trust": 100, "tier": 1, "description": "United Nations treaty collection and international law."},
        {"title": "World Legal Information Institute", "url": "https://www.worldlii.org/", "trust": 85, "tier": 1, "description": "Free global legal information from multiple jurisdictions."},
        {"title": "Stanford Encyclopedia - Philosophy of Law", "url": "https://plato.stanford.edu/entries/law-philosophy/", "trust": 100, "tier": 1, "description": "SEP entry on jurisprudence and legal philosophy."},
        {"title": "ICJ - International Court of Justice", "url": "https://www.icj-cij.org/", "trust": 100, "tier": 1, "description": "ICJ judgments, advisory opinions, and orders."},
        {"title": "Google Scholar - Legal Opinions", "url": "https://scholar.google.com/schhp?as_sdt=4", "trust": 70, "tier": 2, "description": "Google Scholar case law search and legal opinions."},
    ],
    "Geopolitics": [
        {"title": "Geopolitics - Wikipedia", "url": "https://en.wikipedia.org/wiki/Geopolitics", "trust": 70, "tier": 2, "description": "Overview of geopolitics, theory, and international relations."},
        {"title": "Council on Foreign Relations", "url": "https://www.cfr.org/", "trust": 85, "tier": 1, "description": "US think tank for foreign policy and international affairs."},
        {"title": "Chatham House", "url": "https://www.chathamhouse.org/", "trust": 100, "tier": 1, "description": "Royal Institute of International Affairs, policy research."},
        {"title": "International Crisis Group", "url": "https://www.crisisgroup.org/", "trust": 85, "tier": 1, "description": "Independent organization preventing and resolving conflict."},
        {"title": "RAND Corporation", "url": "https://www.rand.org/topics/international-affairs.html", "trust": 100, "tier": 1, "description": "Research on international security and geopolitical issues."},
        {"title": "Brookings Institution", "url": "https://www.brookings.edu/topic/international-affairs/", "trust": 85, "tier": 1, "description": "US think tank foreign policy research."},
        {"title": "United Nations", "url": "https://www.un.org/en/our-work", "trust": 100, "tier": 1, "description": "UN peace, security, and international cooperation."},
        {"title": "Strategic Studies Institute", "url": "https://ssi.armywarcollege.edu/", "trust": 85, "tier": 1, "description": "US Army War College geopolitical and security research."},
        {"title": "Wilson Center", "url": "https://www.wilsoncenter.org/", "trust": 85, "tier": 1, "description": "US think tank for international scholarship and dialogue."},
        {"title": "SSRN International Relations", "url": "https://papers.ssrn.com/sol3/JELJOUR_Results.cfm", "trust": 85, "tier": 1, "description": "Social Science Research Network IR preprints."},
    ],
    "Linguistics": [
        {"title": "Linguistics - Wikipedia", "url": "https://en.wikipedia.org/wiki/Linguistics", "trust": 70, "tier": 2, "description": "Overview of linguistics, its branches, and methods."},
        {"title": "Linguistic Society of America", "url": "https://www.linguisticsociety.org/", "trust": 95, "tier": 1, "description": "Professional society for linguistics research and education."},
        {"title": "ArXiv Computation and Language", "url": "https://arxiv.org/list/cs.CL/new", "trust": 100, "tier": 1, "description": "Preprints in computational linguistics and NLP (cs.CL)."},
        {"title": "ACL - Association for Computational Linguistics", "url": "https://www.aclweb.org/portal/", "trust": 100, "tier": 1, "description": "Leading professional society for NLP and CL."},
        {"title": "Ethnologue", "url": "https://www.ethnologue.com/", "trust": 70, "tier": 2, "description": "Comprehensive database of world languages."},
        {"title": "Stanford Encyclopedia - Linguistics", "url": "https://plato.stanford.edu/entries/linguistics/", "trust": 100, "tier": 1, "description": "SEP entry on the philosophy of linguistics."},
        {"title": "Glottolog", "url": "https://glottolog.org/", "trust": 100, "tier": 1, "description": "Comprehensive reference for world languages and language families."},
        {"title": "Oxford Linguistics", "url": "https://www.oxfordbibliographies.com/linguistics", "trust": 95, "tier": 1, "description": "Oxford bibliographies in linguistics."},
        {"title": "MIT Linguistics", "url": "https://linguistics.mit.edu/", "trust": 100, "tier": 1, "description": "MIT Department of Linguistics and Philosophy."},
        {"title": "Journal of Linguistics", "url": "https://www.cambridge.org/core/journals/journal-of-linguistics", "trust": 95, "tier": 1, "description": "Cambridge University Press linguistics journal."},
    ],
    "Psychology": [
        {"title": "Psychology - Wikipedia", "url": "https://en.wikipedia.org/wiki/Psychology", "trust": 70, "tier": 2, "description": "Overview of psychology, its branches, and history."},
        {"title": "APA - American Psychological Association", "url": "https://www.apa.org/", "trust": 100, "tier": 1, "description": "Leading US professional organization for psychology."},
        {"title": "PubMed Psychology", "url": "https://pubmed.ncbi.nlm.nih.gov/?term=psychology", "trust": 100, "tier": 1, "description": "PubMed search filtered to psychological research."},
        {"title": "NCBI Bookshelf - Psychology", "url": "https://www.ncbi.nlm.nih.gov/books/NBK310/", "trust": 100, "tier": 1, "description": "Free psychology textbooks and resources from NCBI."},
        {"title": "Nature Human Behaviour", "url": "https://www.nature.com/nathumbehav/", "trust": 95, "tier": 1, "description": "Journal publishing research in psychology and behavioral science."},
        {"title": "Stanford Encyclopedia - Psychology", "url": "https://plato.stanford.edu/entries/psychology/", "trust": 100, "tier": 1, "description": "SEP entry on the philosophy of psychology."},
        {"title": "BPS - British Psychological Society", "url": "https://www.bps.org.uk/", "trust": 95, "tier": 1, "description": "UK professional body for psychology."},
        {"title": "PsycINFO via APA", "url": "https://www.apa.org/pubs/databases/psycinfo", "trust": 100, "tier": 1, "description": "APA database of psychological literature."},
        {"title": "NIH - National Institute of Mental Health", "url": "https://www.nimh.nih.gov/", "trust": 100, "tier": 1, "description": "US federal agency for mental health research."},
        {"title": "Annual Review of Psychology", "url": "https://www.annualreviews.org/journal/psych", "trust": 100, "tier": 1, "description": "Comprehensive review articles in psychology."},
    ],
    "Sociology": [
        {"title": "Sociology - Wikipedia", "url": "https://en.wikipedia.org/wiki/Sociology", "trust": 70, "tier": 2, "description": "Overview of sociology, its theories, and methods."},
        {"title": "American Sociological Association", "url": "https://www.asanet.org/", "trust": 100, "tier": 1, "description": "Leading US professional organization for sociology."},
        {"title": "SSRN Sociology", "url": "https://papers.ssrn.com/sol3/JELJOUR_Results.cfm", "trust": 85, "tier": 1, "description": "Social Science Research Network sociology preprints."},
        {"title": "SocArXiv", "url": "https://osf.io/preprints/socarxiv", "trust": 85, "tier": 1, "description": "Open access preprint server for sociology."},
        {"title": "NCES - National Center for Education Statistics", "url": "https://nces.ed.gov/", "trust": 100, "tier": 1, "description": "US federal education data and sociological research."},
        {"title": "Pew Research Center", "url": "https://www.pewresearch.org/", "trust": 90, "tier": 1, "description": "Nonpartisan US think tank on social and demographic trends."},
        {"title": "Stanford Encyclopedia - Sociology", "url": "https://plato.stanford.edu/entries/sociology/", "trust": 100, "tier": 1, "description": "SEP entry on the philosophy of social science."},
        {"title": "Bureau of Labor Statistics", "url": "https://www.bls.gov/", "trust": 100, "tier": 1, "description": "US federal agency for labor economics and social statistics."},
        {"title": "National Opinion Research Center", "url": "https://www.norc.org/", "trust": 95, "tier": 1, "description": "University of Chicago social science research organization."},
        {"title": "Annual Review of Sociology", "url": "https://www.annualreviews.org/journal/soc", "trust": 100, "tier": 1, "description": "Comprehensive review articles in sociology."},
    ],
    "EnvironmentalScience": [
        {"title": "Environmental Science - Wikipedia", "url": "https://en.wikipedia.org/wiki/Environmental_science", "trust": 70, "tier": 2, "description": "Overview of environmental science and its interdisciplinary nature."},
        {"title": "EPA - Environmental Protection Agency", "url": "https://www.epa.gov/", "trust": 100, "tier": 1, "description": "US federal agency for environmental protection and research."},
        {"title": "NOAA - Climate", "url": "https://www.noaa.gov/climate", "trust": 100, "tier": 1, "description": "National Oceanic and Atmospheric Administration climate data."},
        {"title": "Nature Climate Change", "url": "https://www.nature.com/nclimate/", "trust": 100, "tier": 1, "description": "Leading journal on climate change research."},
        {"title": "IPCC Reports", "url": "https://www.ipcc.ch/", "trust": 100, "tier": 1, "description": "Intergovernmental Panel on Climate Change assessment reports."},
        {"title": "UNEP - UN Environment Programme", "url": "https://www.unep.org/", "trust": 100, "tier": 1, "description": "United Nations environmental data and policy."},
        {"title": "ArXiv Atmospheric Physics", "url": "https://arxiv.org/list/physics.ao-ph/new", "trust": 100, "tier": 1, "description": "Preprints in atmospheric and oceanic physics."},
        {"title": "NASA Earth Observatory", "url": "https://earthobservatory.nasa.gov/", "trust": 100, "tier": 1, "description": "NASA satellite imagery and environmental science data."},
        {"title": "USGS - Water Resources", "url": "https://www.usgs.gov/mission-areas/water-resources", "trust": 100, "tier": 1, "description": "US Geological Survey water and environmental data."},
        {"title": "Annual Review of Environment and Resources", "url": "https://www.annualreviews.org/journal/energy", "trust": 100, "tier": 1, "description": "Comprehensive review articles in environmental science."},
    ],
}

for domain, sources in SEEDS.items():
    path = SEED_DIR / f"{domain}.json"
    with open(path, "w", encoding="utf-8") as f:
        json.dump(sources, f, indent=2)
    print(f"{domain}: {len(sources)} seeds -> {path}")

print(f"\nDone. {len(SEEDS)} domain seed files created in {SEED_DIR}")
